export const messages = [
  { sender: "Person 1", message: "Hello" },
  { sender: "Person 2", message: "Hi" },
  { sender: "Person 1", message: "How are you?" },
  { sender: "Person 2", message: "I'm fine" },
  { sender: "Person 1", message: "That's great to hear!" },
  { sender: "Person 2", message: "Thanks!" },
  { sender: "Person 2", message: "And you?" },
  { sender: "Person 1", message: "I'm doing well too, thanks for asking." },
  { sender: "Person 1", message: "What have you been up to lately?" },
  {
    sender: "Person 2",
    message: "Not much, just working and hanging out with friends.",
  },
  { sender: "Person 1", message: "Sounds like fun!" },
  { sender: "Person 2", message: "Yeah, it's been pretty good." },
  { sender: "Person 2", message: "How about you?" },
  {
    sender: "Person 1",
    message: "I've been busy with work as well, but I'm managing.",
  },
  { sender: "Person 1", message: "Anyway, got to go now. Talk to you later!" },
  { sender: "Person 2", message: "Sure, talk to you later. Bye!" },
  { sender: "Person 1", message: "Hello again!" },
  { sender: "Person 2", message: "Hey there!" },
  { sender: "Person 1", message: "How's your day going?" },
  { sender: "Person 2", message: "Pretty good, thanks for asking." },
  { sender: "Person 1", message: "I'm glad to hear that." },
  { sender: "Person 2", message: "Yeah, it's been quite productive." },
  { sender: "Person 2", message: "How about you?" },
  { sender: "Person 1", message: "I'm just relaxing at home." },
  {
    sender: "Person 1",
    message: "By the way, did you watch the latest episode of that show?",
  },
  { sender: "Person 2", message: "Not yet, I'm planning to watch it tonight." },
  {
    sender: "Person 1",
    message: "It's really good, you should definitely check it out.",
  },
  { sender: "Person 2", message: "Thanks for the recommendation." },
  { sender: "Person 1", message: "No problem!" },
  { sender: "Person 2", message: "Hey, I need to ask you something." },
  { sender: "Person 1", message: "Sure, what is it?" },
  {
    sender: "Person 2",
    message: "Have you heard about the new restaurant that opened downtown?",
  },
  {
    sender: "Person 1",
    message: "Yeah, I heard about it. I heard the food is really good.",
  },
  { sender: "Person 2", message: "We should go check it out sometime." },
  { sender: "Person 1", message: "Definitely, let's plan it." },
  { sender: "Person 1", message: "Gotta go now, talk to you later!" },
  { sender: "Person 2", message: "Alright, take care. Bye!" },
  // Repeating some of the previous messages to reach 100 messages
  { sender: "Person 1", message: "Hello" },
  { sender: "Person 2", message: "Hi" },
  { sender: "Person 1", message: "How are you?" },
  { sender: "Person 2", message: "I'm fine" },
  { sender: "Person 1", message: "That's great to hear!" },
  { sender: "Person 2", message: "Thanks!" },
  { sender: "Person 2", message: "And you?" },
  { sender: "Person 1", message: "I'm doing well too, thanks for asking." },
  { sender: "Person 1", message: "What have you been up to lately?" },
  {
    sender: "Person 2",
    message: "Not much, just working and hanging out with friends.",
  },
  { sender: "Person 1", message: "Sounds like fun!" },
  { sender: "Person 2", message: "Yeah, it's been pretty good." },
  { sender: "Person 2", message: "How about you?" },
  {
    sender: "Person 1",
    message: "I've been busy with work as well, but I'm managing.",
  },
  { sender: "Person 1", message: "Anyway, got to go now. Talk to you later!" },
  { sender: "Person 2", message: "Sure, talk to you later. Bye!" },
  { sender: "Person 1", message: "Hello" },
  { sender: "Person 2", message: "Hi" },
  { sender: "Person 1", message: "How are you?" },
  { sender: "Person 2", message: "I'm fine" },
  { sender: "Person 1", message: "That's great to hear!" },
  { sender: "Person 2", message: "Thanks!" },
  { sender: "Person 2", message: "And you?" },
  { sender: "Person 1", message: "I'm doing well too, thanks for asking." },
  { sender: "Person 1", message: "What have you been up to lately?" },
  {
    sender: "Person 2",
    message: "Not much, just working and hanging out with friends.",
  },
  { sender: "Person 1", message: "Sounds like fun!" },
  { sender: "Person 2", message: "Yeah, it's been pretty good." },
  { sender: "Person 2", message: "How about you?" },
  {
    sender: "Person 1",
    message: "I've been busy with work as well, but I'm managing.",
  },
  { sender: "Person 1", message: "Anyway, got to go now. Talk to you later!" },
  { sender: "Person 2", message: "Sure, talk to you later. Bye!" },
  { sender: "Person 1", message: "Hello again!" },
  { sender: "Person 2", message: "Hey there!" },
  { sender: "Person 1", message: "How's your day going?" },
  { sender: "Person 2", message: "Pretty good, thanks for asking." },
  { sender: "Person 1", message: "I'm glad to hear that." },
  { sender: "Person 2", message: "Yeah, it's been quite productive." },
  { sender: "Person 2", message: "How about you?" },
  { sender: "Person 1", message: "I'm just relaxing at home." },
  {
    sender: "Person 1",
    message: "By the way, did you watch the latest episode of that show?",
  },
  { sender: "Person 2", message: "Not yet, I'm planning to watch it tonight." },
  {
    sender: "Person 1",
    message: "It's really good, you should definitely check it out.",
  },
  { sender: "Person 2", message: "Thanks for the recommendation." },
  { sender: "Person 1", message: "No problem!" },
  { sender: "Person 2", message: "Hey, I need to ask you something." },
  { sender: "Person 1", message: "Sure, what is it?" },
  {
    sender: "Person 2",
    message: "Have you heard about the new restaurant that opened downtown?",
  },
  {
    sender: "Person 1",
    message: "Yeah, I heard about it. I heard the food is really good.",
  },
  { sender: "Person 2", message: "We should go check it out sometime." },
  { sender: "Person 1", message: "Definitely, let's plan it." },
  { sender: "Person 1", message: "Gotta go now, talk to you later!" },
  { sender: "Person 2", message: "Alright, take care. Bye!" },
  // Repeating some of the previous messages to reach 100 messages
  { sender: "Person 1", message: "Hello" },
  { sender: "Person 2", message: "Hi" },
  { sender: "Person 1", message: "How are you?" },
  { sender: "Person 2", message: "I'm fine" },
  { sender: "Person 1", message: "That's great to hear!" },
  { sender: "Person 2", message: "Thanks!" },
  { sender: "Person 2", message: "And you?" },
  { sender: "Person 1", message: "I'm doing well too, thanks for asking." },
  { sender: "Person 1", message: "What have you been up to lately?" },
  {
    sender: "Person 2",
    message: "Not much, just working and hanging out with friends.",
  },
  { sender: "Person 1", message: "Sounds like fun!" },
  { sender: "Person 2", message: "Yeah, it's been pretty good." },
  { sender: "Person 2", message: "How about you?" },
  {
    sender: "Person 1",
    message: "I've been busy with work as well, but I'm managing.",
  },
  { sender: "Person 1", message: "Anyway, got to go now. Talk to you later!" },
  { sender: "Person 2", message: "Sure, talk to you later. Bye!" },
  { sender: "Person 1", message: "Hello" },
  { sender: "Person 2", message: "Hi" },
  { sender: "Person 1", message: "How are you?" },
  { sender: "Person 2", message: "I'm fine" },
  { sender: "Person 1", message: "That's great to hear!" },
  { sender: "Person 2", message: "Thanks!" },
  { sender: "Person 2", message: "And you?" },
  { sender: "Person 1", message: "I'm doing well too, thanks for asking." },
  { sender: "Person 1", message: "What have you been up to lately?" },
  {
    sender: "Person 2",
    message: "Not much, just working and hanging out with friends.",
  },
  { sender: "Person 1", message: "Sounds like fun!" },
  { sender: "Person 2", message: "Yeah, it's been pretty good." },
  { sender: "Person 2", message: "How about you?" },
  {
    sender: "Person 1",
    message: "I've been busy with work as well, but I'm managing.",
  },
  { sender: "Person 1", message: "Anyway, got to go now. Talk to you later!" },
  { sender: "Person 2", message: "Sure, talk to you later. Bye!" },
  { sender: "Person 1", message: "Hello again!" },
  { sender: "Person 2", message: "Hey there!" },
  { sender: "Person 1", message: "How's your day going?" },
  { sender: "Person 2", message: "Pretty good, thanks for asking." },
  { sender: "Person 1", message: "I'm glad to hear that." },
  { sender: "Person 2", message: "Yeah, it's been quite productive." },
  { sender: "Person 2", message: "How about you?" },
  { sender: "Person 1", message: "I'm just relaxing at home." },
  {
    sender: "Person 1",
    message: "By the way, did you watch the latest episode of that show?",
  },
  { sender: "Person 2", message: "Not yet, I'm planning to watch it tonight." },
  {
    sender: "Person 1",
    message: "It's really good, you should definitely check it out.",
  },
  { sender: "Person 2", message: "Thanks for the recommendation." },
  { sender: "Person 1", message: "No problem!" },
  { sender: "Person 2", message: "Hey, I need to ask you something." },
  { sender: "Person 1", message: "Sure, what is it?" },
  {
    sender: "Person 2",
    message: "Have you heard about the new restaurant that opened downtown?",
  },
  {
    sender: "Person 1",
    message: "Yeah, I heard about it. I heard the food is really good.",
  },
  { sender: "Person 2", message: "We should go check it out sometime." },
  { sender: "Person 1", message: "Definitely, let's plan it." },
  { sender: "Person 1", message: "Gotta go now, talk to you later!" },
  { sender: "Person 2", message: "Alright, take care. Bye!" },
  // Repeating some of the previous messages to reach 100 messages
  { sender: "Person 1", message: "Hello" },
  { sender: "Person 2", message: "Hi" },
  { sender: "Person 1", message: "How are you?" },
  { sender: "Person 2", message: "I'm fine" },
  { sender: "Person 1", message: "That's great to hear!" },
  { sender: "Person 2", message: "Thanks!" },
  { sender: "Person 2", message: "And you?" },
  { sender: "Person 1", message: "I'm doing well too, thanks for asking." },
  { sender: "Person 1", message: "What have you been up to lately?" },
  {
    sender: "Person 2",
    message: "Not much, just working and hanging out with friends.",
  },
  { sender: "Person 1", message: "Sounds like fun!" },
  { sender: "Person 2", message: "Yeah, it's been pretty good." },
  { sender: "Person 2", message: "How about you?" },
  {
    sender: "Person 1",
    message: "I've been busy with work as well, but I'm managing.",
  },
  { sender: "Person 1", message: "Anyway, got to go now. Talk to you later!" },
  { sender: "Person 2", message: "Sure, talk to you later. Bye!" },
  { sender: "Person 1", message: "Hello" },
  { sender: "Person 2", message: "Hi" },
  { sender: "Person 1", message: "How are you?" },
  { sender: "Person 2", message: "I'm fine" },
  { sender: "Person 1", message: "That's great to hear!" },
  { sender: "Person 2", message: "Thanks!" },
  { sender: "Person 2", message: "And you?" },
  { sender: "Person 1", message: "I'm doing well too, thanks for asking." },
  { sender: "Person 1", message: "What have you been up to lately?" },
  {
    sender: "Person 2",
    message: "Not much, just working and hanging out with friends.",
  },
  { sender: "Person 1", message: "Sounds like fun!" },
  { sender: "Person 2", message: "Yeah, it's been pretty good." },
  { sender: "Person 2", message: "How about you?" },
  {
    sender: "Person 1",
    message: "I've been busy with work as well, but I'm managing.",
  },
  { sender: "Person 1", message: "Anyway, got to go now. Talk to you later!" },
  { sender: "Person 2", message: "Sure, talk to you later. Bye!" },
  { sender: "Person 1", message: "Hello again!" },
  { sender: "Person 2", message: "Hey there!" },
  { sender: "Person 1", message: "How's your day going?" },
  { sender: "Person 2", message: "Pretty good, thanks for asking." },
  { sender: "Person 1", message: "I'm glad to hear that." },
  { sender: "Person 2", message: "Yeah, it's been quite productive." },
  { sender: "Person 2", message: "How about you?" },
  { sender: "Person 1", message: "I'm just relaxing at home." },
  {
    sender: "Person 1",
    message: "By the way, did you watch the latest episode of that show?",
  },
  { sender: "Person 2", message: "Not yet, I'm planning to watch it tonight." },
  {
    sender: "Person 1",
    message: "It's really good, you should definitely check it out.",
  },
  { sender: "Person 2", message: "Thanks for the recommendation." },
  { sender: "Person 1", message: "No problem!" },
  { sender: "Person 2", message: "Hey, I need to ask you something." },
  { sender: "Person 1", message: "Sure, what is it?" },
  {
    sender: "Person 2",
    message: "Have you heard about the new restaurant that opened downtown?",
  },
  {
    sender: "Person 1",
    message: "Yeah, I heard about it. I heard the food is really good.",
  },
  { sender: "Person 2", message: "We should go check it out sometime." },
  { sender: "Person 1", message: "Definitely, let's plan it." },
  { sender: "Person 1", message: "Gotta go now, talk to you later!" },
  { sender: "Person 2", message: "Alright, take care. Bye!" },
  // Repeating some of the previous messages to reach 100 messages
  { sender: "Person 1", message: "Hello" },
  { sender: "Person 2", message: "Hi" },
  { sender: "Person 1", message: "How are you?" },
  { sender: "Person 2", message: "I'm fine" },
  { sender: "Person 1", message: "That's great to hear!" },
  { sender: "Person 2", message: "Thanks!" },
  { sender: "Person 2", message: "And you?" },
  { sender: "Person 1", message: "I'm doing well too, thanks for asking." },
  { sender: "Person 1", message: "What have you been up to lately?" },
  {
    sender: "Person 2",
    message: "Not much, just working and hanging out with friends.",
  },
  { sender: "Person 1", message: "Sounds like fun!" },
  { sender: "Person 2", message: "Yeah, it's been pretty good." },
  { sender: "Person 2", message: "How about you?" },
  {
    sender: "Person 1",
    message: "I've been busy with work as well, but I'm managing.",
  },
  { sender: "Person 1", message: "Anyway, got to go now. Talk to you later!" },
  { sender: "Person 2", message: "Sure, talk to you later. Bye!" },
  { sender: "Person 1", message: ":)" },
  { sender: "Person 2", message: ":D" },
];

export const names = [
  "Sophia Johnson",
  "Liam Smith",
  "Olivia Brown",
  "Noah Davis",
  "Emma Wilson",
  "Jackson Martinez",
  "Ava Anderson",
  "Lucas Thomas",
  "Isabella Garcia",
  "Oliver Rodriguez",
  "Mia Martinez",
  "Elijah Hernandez",
  "Charlotte Lopez",
  "Grayson Lee",
  "Amelia Gonzalez",
  "Mateo Perez",
  "Harper Adams",
  "Ethan Baker",
  "Evelyn White",
  "Logan Green",
];
